Feat/#11 week4 compose 필수 과제 구현
NOW-SOPT-ANDROID/hyeumm-song pull request #13
Opened 2024-05-03 14:09 UTC by hyeumm

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- #11 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- [x] 로그인을 서버통신을 통해 다른 기기에서 로그인을 시도시에도 성공할 수 있게 해주세요
- [x] 로그인 성공 / 실패 여부에 따라서
- [x] 내 정보를 구현
    - 로그인이 성공했을 시, UserId (로그인 할 때 id 아님 주의) 를 토스트 메세지에 넣어주세요! (세미나 자료 참고)
    
## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/NOW-SOPT-ANDROID/hyeumm-song/assets/118244028/ecd9da3d-4c21-4613-b671-0cf7a5b78c3f

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
홈 프래그먼트 팔로워랑 비밀번호 부분을 아직 완성못했는데 완성하는대로 바로 푸쉬하겠습니다!

api 연결은 컴포즈와 xml 코드가 거의 동일하게 작성되었습니다..!
코리 남겨주시면 열심히열심히 반영하겠습니다..!

## 코리 반영하기

2024-05-03 16:30 UTC, l2hyunwoo requested changes
안녕하세요 혜음님. 안드로이드 파트 명예 OB 이현우입니다. 만나서 반갑습니다.

앞으로의 과제들에 대한 코드리뷰를 맡게 되었습니다. 고민해보시다가 궁금한 점이 있으시면 지식 공유방/디스코드 연락 해주세요. 대면/비대면 자유형식으로 추가 피드백 가능합니다. 

우선 과제 어려우셨을텐데 빠르게 과제 수행해주신점 너무 좋습니다. 관련해서 추가적으로 피드백/질문 남긴 것들이 있습니다. 질문을 남긴 경우 코드에 문제가 있어서 질문이 남긴 것이 아니고 정말 혜음님의 작성 의도가 궁금해서 남긴 것이니 이 점 참고해주시면 감사하겠습니다.

앞으로 잘 부탁드리겠습니다.

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/HomeScreen.kt
> +fun HomeScreen(viewModel: HomeViewModel) {
```suggestion
fun HomeScreen(viewModel: HomeViewModel = viewModel()) {
```

Compose에서 ViewModel은 함수 내에서 멤버변수로 직접 사용하거나 매개변수로 주입받는 경우에는 이런식으로 디폴트 매개변수로 주입받아서 호출부에서는

```kotlin
HomeScreen()
```

으로만 사용할 수 있게 작성하는 경향이 있습니다. 이 역시 취향의 영역이니 다른 분들 코드 종합적으로 보고, 직접 코드를 적어보시면서 어떤게 더 좋을지 판단해보시는 것이 좋을 것 같아요.

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +    private val viewModel by viewModels<LoginViewModel>()
View 기반에서는 이와 같이 선언을 해도 되지만, 저희는 Compose를 사용하니 이 방식보다는 Compose 코드 내부에서 선언을 해보는 방식으로 변경해보는 것도 좋을 것 같습니다.

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +            ).show()
컴포즈 내부에서는 이런 상태들이나 이벤트들을 관찰해서 처리를 할 수 없을까요? 어떻게 구현해야 컴포즈 내부에서 상태/이벤트를 처리할 수 있을까요?

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +                intent.putExtra("userId", viewModel.userId)
지금은 Intent 기반으로 화면이동을 하지만 이후에는 Compose-navigation을 사용하시면서 화면전환 로직 구축해보는 것도 좋을 것 같습니다.

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +        onPwChange: (String) -> Unit
축약어는 지양하시는 것이 가독성에 좋습니다. pw -> password로 변경해보면 어떨까요?

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/LoginViewModel.kt
> +    val liveData = MutableLiveData<LoginState>()
liveData는 어떤 데이터를 말하는거죠? 다른 개발자가 보기에 liveData가 어떤 데이터를 표현하는지 한 눈에 알아볼 수 있을까요? 

지금은 혼자서 과제를 수행하고 있기 때문에 변수명을 크게 신경쓰지 않아도 되지만, 이후에 다른 개발자들과 협업을 할때를 대비해서라도 미리미리 변수명을 더 가독성 있게 지어보는 것도 습관 들이시는 것이 좋을 것 같습니다.

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/LoginViewModel.kt
> +    private val authService by lazy { ServicePool.authService }
authService 변수를 lazy로 가져올 필요가 있을까요?

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/LoginViewModel.kt
> +    var userId : String?= ""
userId역시 화면의 상태에 영향을 주는 친구이기 때문에 따로 변수를 지으시면 이후 화면을 그리는 상태를 관리할 때 어려움을 겪을 수도 있을 것 같아요.

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +    private var userPhone: String = ""// 변수를 이렇게 여기에 선언해도 괜찮은지...
사실 화면 전역에서 사용하기 편하려면 이것보다 더 나은 방법이 없긴 합니다. 저도 이 방식을 많이 사용하구요. 다만 기본값이 null로 설정하거나 빈값으로 설정하는건 각 케이스가 어떤지에 따라서 달라집니다.

- 빈값이 실제로 들어올 수 있는 경우: null을 기본값으로 쓰거나 클래스형태로 응답값을 포장해서 사용합니다. 그래야 이게 제대로 값이 들어온건지 안들어온건지 판단을 쉽게 할 수 있습니다.
- 실제로 빈값이 들어오면 절대 안되는 경우: 기본값 빈 스트링으로 지정합니다. 빈 스트링이면 어떤 로직도 처리하지 못하게 만들어버리면 쉽게 로직 구현 가능해지더라구요.

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +    }
함수분리 좋습니다.

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
>                      }
selectedItem이 무엇이 있는지 모르는데 다른 개발자들이 0, 1, 2가 어떤건지 알고 추가적인 코드리뷰를 할 수 있을까요...? 물론 여기에서는 대략 홈, 검색, 프로필 화면인 것을 인지할 수 있긴 합니다만 코드가 좀만 더 길어지면 코드 보기가 더 어려워질 수 있으니 이 점 유의해서 코드 작성해주시면 좋을 것 같아요.

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +                        onPhoneChange = { phone = it })
함수의 경우를 제외하고, 변수의 경우에는 각 패러미터에 어떤 값들이 들어가야 하는지 명시가 안되어있어서 에러를 일으킬 가능성이 농후해집니다. 컴포즈에서는 named argument 꼭 활용하시길 바랍니다.

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +                    var phone by remember { mutableStateOf("") }
축약어 지양해주세요.

pw, nick

2024-05-03 16:30 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +        }
Toast는 따지고 보면 화면에 영원히 띄워질 상태가 아니고 한번 띄워지고 말아야하는 상황이자나요. 지금 구현된 코드 기반에서는 화면 회전을 하거나 다크모드 전환을 했을 때 토스트가 한번 더 띄워질 수 있는 코드로 보여집니다. 확인 부탁드립니다.

2024-05-05 12:28 UTC, boiledEgg-s approved these changes
이번주도 너무 고생하셨어요!! 남은 부분은 후딱 해서 올려주세요~ 3조 더욱 열심히 정진합시다~

2024-05-05 13:48 UTC, chattymin requested changes
고생하셨습니다!!!
xml과 공통되는 부분은 일부러 코멘트 안달았으니 xml에 달린 것들은 여기서도 수정부탁드립니다!!

2024-05-05 13:48 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/UserService.kt
> +}
헤더도 인터셉터로 넣어봐요~

2024-05-05 13:48 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +            )
중복되는 친구들은 component로 빼보는건 어떨까용

2024-05-05 14:06 UTC, youjin09222 approved these changes
이번 주차도 고생하셨습니다👏👏
저도 xml과 거의 동일하게 구현해서 반갑네요...
이번주에 같이 보완해봅시다!!

2024-05-05 14:58 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +            ).show()
오 저는 xml 그대로 사용하려다가 오류가 났었는데 해결하셨네요?? 일단 저는 observeAsState()를 사용했습니다!

2024-05-06 17:05 UTC, hyeumm commented
> 안녕하세요 혜음님. 안드로이드 파트 명예 OB 이현우입니다. 만나서 반갑습니다.
> 
> 앞으로의 과제들에 대한 코드리뷰를 맡게 되었습니다. 고민해보시다가 궁금한 점이 있으시면 지식 공유방/디스코드 연락 해주세요. 대면/비대면 자유형식으로 추가 피드백 가능합니다.
> 
> 우선 과제 어려우셨을텐데 빠르게 과제 수행해주신점 너무 좋습니다. 관련해서 추가적으로 피드백/질문 남긴 것들이 있습니다. 질문을 남긴 경우 코드에 문제가 있어서 질문이 남긴 것이 아니고 정말 혜음님의 작성 의도가 궁금해서 남긴 것이니 이 점 참고해주시면 감사하겠습니다.
> 
> 앞으로 잘 부탁드리겠습니다.

안녕하세요! 귀한 시간 내어 코드리뷰 달아주신 점 너무 감사드립니다! 리뷰에 달아주신 내용들은 반영할 수 있는만큼 최대한으로 반영하여 좋은 코드 작성할 수 있도록 노력하겠습니다. 아직 부족한 실력이지만 앞으로 잘부탁드립니다 :)

2024-05-24 14:57 UTC, merged