Feat/#14 week6 xml
NOW-SOPT-ANDROID/hyeumm-song pull request #15
Opened 2024-05-24 14:56 UTC by hyeumm

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- #14

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
    
## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

## 코리 반영하기

2024-05-28 17:05 UTC, chattymin approved these changes
week4에서 거의 같게 가져온 코드같네요!!
수고하셨구 7주차 과제 화이팅입니다 :)

2024-05-28 17:06 UTC, chattymin requested changes
어 다시보니까 이거 main-xml로 합치고 있어요!!!
develop-xml로 머지해야합니다!! 이건 PR 닫아주세요

2024-05-29 11:44 UTC, hyeumm commented
제가 정신이 없어서.. 이런 실수를 해버렸네요.. 방금 base를 바꿨는데 이거로 해결될까요??

2024-05-29 15:26 UTC, chattymin approved these changes
오 대박 base를 바꿀 수 있군요?!!?!?!!?
ㅋㅋㅋㅋㅋㅋㅋ 굿입니다~

2024-05-29 19:00 UTC, youjin09222 approved these changes
👍👍

2024-06-06 06:03 UTC, boiledEgg-s approved these changes
💣

2024-06-07 14:47 UTC, merged