Feat/#5 week2 xml 필수과제 구현
NOW-SOPT-ANDROID/hyeumm-song pull request #7
Opened 2024-04-18 16:35 UTC by hyeumm

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- #5

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- [x] - 마이페이지를 1주차 과제에서 만드셨다면, 마이페이지 탭으로 옮겨주세요.세미나 자료에 있는 바텀 네비게이션과 연동 시켜주세요. 
- [x] - 리스트 위에 기존 Friend 형식과는 다른 **내 프로필**을 디자인 해서 **리스트 상단**에 넣는다.
- [x] - 디자인은 자유입니다, 다만 친구 목록과 대비 되도록 프로필 이미지 사이즈, 혹은 추가적인 디자인적 요소가 필수적으로 탑재되어야 합니다.
- [x] - 데이터는 최소 스크롤이 가능해야 하며, 스크롤시에는 내 프로필 또한 같이 스크롤이 되어야합니다.
    - 즉 내 프로필을 RecyclerView 외부에 위치시킨다면 같이 스크롤이 되지 않기 때문에 내부에 위치시킬 수 있는 방법을 찾아봅시다
    - Multi-View Type RecyclerView 또는 ConcatAdapter
    
## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
https://github.com/NOW-SOPT-ANDROID/hyeumm-song/assets/118244028/331319cf-4f7f-4231-a886-89bd40676b34

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
이번 주차 과제에 뷰모델을 적용해보려고 했는데..다른 자잘자잘한 부분에 집중하다보니 미처 시도하지 못했습니다..
시험이 끝나면 무조건 뷰모델부터 구현할게요!!
항상 부족한 코드가 많지만 리뷰달아주시면 최선을 다해서 반영해보겠습니닷..!!

## 코리 반영하기

2024-04-20 04:28 UTC, chattymin requested changes
코멘트를 빨아들이는 속도가 스펀지 뺨치네요
제 모든코드 호로록 가져가시길 바랍니다 ㅋㅋ

2024-04-20 04:28 UTC, chattymin commented on app/src/main/java/com/sopt/now/HomeFragment.kt
> +}
fragment의 경우 lifecycle이 복잡합니다!
그렇기 때문에 반드시 binding을 해제해주는 로직이 필요합니다.
이건 꼭 수정하시기 바랍니다!
[참고링크](https://wooooooak.github.io/android/2019/08/05/fragment%EC%83%9D%EB%AA%85%EC%A3%BC%EA%B8%B0%EC%99%80%EA%B0%9D%EC%B2%B4%ED%8C%8C%EA%B4%B4%EC%8B%9C%EC%A0%90/)

2024-04-20 04:28 UTC, chattymin commented on app/src/main/java/com/sopt/now/HomeListAdapter.kt
> +                holder.setIsRecyclable(false)
with를 활용해보면 좋을것 같아요~

2024-04-20 04:28 UTC, chattymin commented on app/src/main/java/com/sopt/now/HomeListData.kt
> +object HomeListData {
이런 데이터들을 담아서 사용하는 ViewModel을 배웠었죠!
적용해봅시다 :)

2024-04-20 04:28 UTC, chattymin commented on app/src/main/java/com/sopt/now/HomeListViewHolder.kt
> +    val tvSelfDescription: TextView = view.findViewById(R.id.tv_self_description)
헉.
findViewById는 사용 금지!!!!!!!!!!!!!!!!!!
다른 방법을 찾아봅시다!!!!!!!!!

2024-04-20 04:28 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +            startActivity(intent)
Scope 함수를 활용해봐용~

2024-04-20 04:28 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    }
헉 sharedPreference 너무 좋아요!!
그런데 데이터를 가져오는 과정은 View보다는 ViewModel에 적합한 코드 같네요!! 수정해볼까용~

2024-04-20 04:28 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +            userId != id || userPw != pw -> getString(R.string.login_error_different)
비어있는것을 파악하기위해서는 `A == ""` 보다 `isEmpty` 혹은 `isBlank`를 활용하면 가독성이 올라가요~

2024-04-20 04:28 UTC, chattymin commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +    }
굿!!!! 완벽하네요

2024-04-20 04:28 UTC, chattymin commented on app/src/main/res/layout/item_user.xml
> +        android:text="사용자의 이름"
text기본값을 넣어뒀다가, 사용자의 이름을 받아오면 덮어쓰기 하는 코드 같습니다.
그렇다면 서버로부터 값을 받아오는데 시간이 오래 걸리거나, 받아오는 과정에서 에러가 난다면 기본값이 노출됩니다.

그렇기 때문에 `tools:text`를 활용한다면 split에서는 들어가있는게 보이지만, 실제로는 안보이는. 개발을 위해서 쓸 수 있습니다. 전 자주 사용해서 적극 권장해요!

2024-04-21 02:39 UTC, boiledEgg-s approved these changes
코멘트를 달고 싶지만 달게 없네요,, 왜 이렇게 잘하는거야

2024-04-21 02:39 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/HomeListViewHolder.kt
> +    val tvSelfDescription: TextView = view.findViewById(R.id.tv_self_description)
바인딩 객체를 인자로 받아 구현하는 편이 좋겠네요~

2024-04-21 11:24 UTC, youjin09222 commented
너무 잘하시네요!! 👍👍

2024-04-21 11:25 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/HomeListData.kt
리스트 데이터를 따로 저장하니까 좋네요!

2024-04-21 11:31 UTC, youjin09222 approved these changes
너무 잘하시네요!! 👍👍

2024-04-21 11:32 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/HomeListData.kt
리스트 데이터를 따로 저장하니까 좋네요!

2024-04-21 11:34 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/HomeFragment.kt
> +        friendAdapter.setFriendList(MockFriendList.mockFriendList)
리스트 데이터를 따로 저장해서 사용하니까 코드가 확실히 간단해지네요!!

2024-04-21 11:34 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/FriendAdapter.kt
> +            else -> throw RuntimeException("알 수 없는 뷰타입입니다.")
오 예외 처리 좋습니다!

2024-04-21 11:36 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/FriendViewHolder.kt
> +    val tvSelfDescription : TextView = view.findViewById(R.id.tv_self_description)
요기! 바인딩을 쓰면 더 좋을 것 같습니다!

2024-04-21 11:46 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/HomeFragment.kt
> +        homeListAdapter.setHomeList(HomeListData.homeListData)
리스트 데이터를 따로 저장해서 사용하니까 코드가 확실히 간단해지네요!!

2024-04-21 11:51 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/MyPageFragment.kt
> +    }
SharedPreferences를 사용하니까 확실히  코드가 간단하네요!

2024-04-26 13:38 UTC, KwakEuiJin reviewed
갓기 혜음아 엄청난 코드 잘보고 간다 ^&^

2024-04-26 13:38 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/HomeListAdapter.kt
> +                holder.setIsRecyclable(false)
homeListList.getOrNull(position) = 해당 index에 값이 없으면 exception을 던지는 것이 아닌 null을 반환하기 때문에 조금 더 안전한 개발이 가능합니다

2024-04-26 13:38 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/HomeListData.kt
> +        ),
HomeList.VIEW_TYPE_USER 상수를 만들었으니 상수를 활용하는 것이 좋아보여요!

2024-05-01 08:56 UTC, chattymin approved these changes
매주 빠르게 발전하는 코드 잘 보고갑니다!!
최고~

2024-05-01 08:56 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +            }
객체를 생성하지 않고도 가능하답니당!

2024-05-01 08:56 UTC, chattymin commented on app/src/main/java/com/sopt/now/HomeListViewHolder.kt
> +        }
구우우우웃!!!

2024-05-01 14:13 UTC, merged