Feat/#6 week2 compose 필수과제 구현
NOW-SOPT-ANDROID/hyeumm-song pull request #8
Opened 2024-04-18 16:42 UTC by hyeumm

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- #6

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- [x] - 마이페이지를 1주차 과제에서 만드셨다면, 마이페이지 탭으로 옮겨주세요.세미나 자료에 있는 바텀 네비게이션과 연동 시켜주세요. 
- [x] - 리스트 위에 기존 Friend 형식과는 다른 **내 프로필**을 디자인 해서 **리스트 상단**에 넣는다.
- [x] - 디자인은 자유입니다, 다만 친구 목록과 대비 되도록 프로필 이미지 사이즈, 혹은 추가적인 디자인적 요소가 필수적으로 탑재되어야 합니다.
- [x] - 데이터는 최소 스크롤이 가능해야 하며, 스크롤시에는 내 프로필 또한 같이 스크롤이 되어야합니다.
    - 즉 내 프로필을 RecyclerView 외부에 위치시킨다면 같이 스크롤이 되지 않기 때문에 내부에 위치시킬 수 있는 방법을 찾아봅시다
    - Multi-View Type RecyclerView 또는 ConcatAdapter
    
## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/NOW-SOPT-ANDROID/hyeumm-song/assets/118244028/d84bcd70-5d48-43d1-a78e-3b191d6a23c2

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
그래도...1주차때보다는 0.0001%정도 더 컴포즈랑 가까워진것같아요....
제 코드 ... 부족한 점 많지만 리뷰달아주시면 열심히 반영하겠습니다!!!

## 코리 반영하기

2024-04-20 02:00 UTC, boiledEgg-s approved these changes
너무 잘하셔서 할 말이 없네~🐎

2024-04-20 02:00 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +        etc.length !in 1..Int.MAX_VALUE -> R.string.sign_up_etc_error
이렇게 숫자를 하드코딩하는건 안좋다고 합니다!!
 Companion Object에 선언해봐요~

2024-04-20 05:15 UTC, chattymin requested changes
컴포즈도 잘하네요~
채고다 채고

2024-04-20 05:15 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/FriendProfileItem.kt
> +fun FriendProfileItem(friend: Friend) {
friend를 넣어주는 것도 좋지만, 저는 각각 나눠서 넣어주는 것을 더 선호합니다.

만약 friend내부 객체가 바뀐다면?
friend가 아닌 객체도 해당 함수를 재사용하게 된다면?
ui테스트를 위해 Preview를 만들 때 객체도 생성해야 하는 불편함

이런 부분들을 생각해서 저는 image, name, description 등등.. 나눠서 넣어주는걸 선호합니다

2024-04-20 05:15 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +                putExtra("userNick", nick)
숫자를 Companion Object로 빼면서 이것도 빼면 좋을거 같아요~

2024-04-20 05:15 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
>      var pw by remember { mutableStateOf("") }
이름이 UI이기 때문에 id와 pw도 SatateHoisting을 활용해 값을 상단으로 빼는건 어떨까요??
LoginUI에는 UI와 관련된 부분만 존재하고, 값을 수정하거나 클릭했을때의 액션은 밖으로 빼는게 좋아 보입니다!

2024-04-21 12:07 UTC, youjin09222 approved these changes
컴포즈도 잘 하시네요🔥🔥

2024-04-21 12:09 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +        )
중복되는 형식은 함수화해보면 좋을 것 같습니다!

2024-04-21 12:38 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +        )
중복되는 형식은 함수화해보면 좋을 것 같습니다!

2024-05-01 08:44 UTC, chattymin approved these changes
수고하셨습니다!!
노력하신게 보이는 코드네요...!!

2024-05-01 14:13 UTC, merged